baseURL = "https://www.loraserver.io/"
languageCode = "en-us"
relativeURLs = true
title = "LoRa Server, open-source LoRaWAN network-server"
googleAnalytics = "UA-3512995-9"

[[menu.main]]
    pre = "<i class='fas fa-hand-point-right'></i>"
    name = "Overview"
    identifier = "overview"
    url = "/overview/"
    weight = 1

[[menu.main]]
    pre = "<i class='fas fa-download'></i>"
    name = "Install"
    identifier = "install"
    url = "/install/"
    weight = 2

[[menu.main]]
    pre = "<i class='fas fa-user'></i>"
    name = "Use"
    identifier = "use"
    url = "/use/"
    weight = 3

[[menu.main]]
    pre = "<i class='fab fa-github'></i>"
    name = "Community & support"
    identifier = "community"
    url = "/community/"
    weight = 4
